%% ============================================================
% GNN -> COMSOL STATIONARY BDF1
%
% STEP 1:
%   1. Load COMSOL model with the already-computed sol1
%   2. Run Python GNN inference
%   3. Load GNN predictions
%   4. Check COMSOL <-> GNN timestep alignment
%
% Later:
%   5. Configure Stationary BDF1-equivalent problem
%   6. Use GNN prediction as nonlinear initial guess
%   7. Solve timestep by timestep
%   8. Record nonlinear iterations
%
% ============================================================

clear;
clc;
close all;

import com.comsol.model.*
import com.comsol.model.util.*


%% ============================================================
% 1. FILE PATHS
% ============================================================

% COMSOL model.
% Study 1 / sol1 must already have been computed and saved
% by the first MATLAB script.
model_file = ...
    '\\nl-filer1\users$\giovanni\Desktop\Comsol simulations\channel2d_gnn_initial_guess_test.mph';


% Dataset generated by the first MATLAB script
dataset_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\channel2d_physics_variables_gnn_dataset.mat';


% Python executable inside the GNN virtual environment
python_exe = ...
    'C:\Users\giovanni\gnn\.venv\Scripts\python.exe';


% Python inference script
python_script = ...
    'C:\Users\giovanni\gnn\scripts\evaluate_test.py';


% Trained GNN run
run_dir = ...
    'C:\Users\giovanni\gnn\outputs\bsms_powerful_all_geometries_20260904_162806';


% File produced by evaluate_test.py
gnn_predictions_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\gnn_predictions.mat';


%% ============================================================
% 2. LOAD COMSOL MODEL
% ============================================================

fprintf('\n========================================\n');
fprintf('LOADING COMSOL MODEL\n');
fprintf('========================================\n');

model = mphload(model_file);

fprintf('COMSOL model loaded successfully.\n');
fprintf('Model:\n%s\n', model_file);


%% ============================================================
% 3. CHECK TIME-DEPENDENT SOLUTION SOL1
% ============================================================

fprintf('\n========================================\n');
fprintf('CHECKING TIME-DEPENDENT SOLUTION\n');
fprintf('========================================\n');

% Read information specifically from sol1
sol1_info = mphsolinfo(model, 'soltag', 'sol1');

% Stored time values
t_comsol = sol1_info.solvals(:);

num_snapshots = length(t_comsol);
num_transitions = num_snapshots - 1;

fprintf('Number of COMSOL snapshots   = %d\n', num_snapshots);
fprintf('Number of COMSOL transitions = %d\n', num_transitions);

fprintf('Initial time = %.15e s\n', t_comsol(1));
fprintf('Final time   = %.15e s\n', t_comsol(end));

% Time step associated with every transition
dt_comsol = diff(t_comsol);


%% ============================================================
% 4. RUN PYTHON GNN INFERENCE
% ============================================================

fprintf('\n========================================\n');
fprintf('RUNNING GNN INFERENCE\n');
fprintf('========================================\n');

cmd = sprintf( ...
    '"%s" "%s" "%s" --dataset "%s" --no-animation', ...
    python_exe, ...
    python_script, ...
    run_dir, ...
    dataset_file);

fprintf('Python command:\n%s\n\n', cmd);

tic;

[status, python_output] = system(cmd);

gnn_elapsed_time = toc;

% Print Python output in MATLAB
fprintf('%s\n', python_output);

if status ~= 0

    fprintf('\n========================================\n');
    fprintf('GNN INFERENCE FAILED\n');
    fprintf('========================================\n');

    error( ...
        'Python script returned status %d.', ...
        status);

end

fprintf('\n========================================\n');
fprintf('GNN INFERENCE COMPLETED\n');
fprintf('========================================\n');

fprintf('Elapsed time = %.6f s\n', gnn_elapsed_time);


%% ============================================================
% 5. LOAD GNN PREDICTIONS
% ============================================================

fprintf('\n========================================\n');
fprintf('LOADING GNN PREDICTIONS\n');
fprintf('========================================\n');

if ~isfile(gnn_predictions_file)
    error( ...
        'GNN prediction file not found:\n%s', ...
        gnn_predictions_file);
end

G = load(gnn_predictions_file);

num_predictions = size(G.u_pred, 1);
num_nodes = size(G.u_pred, 2);

fprintf('Number of GNN predictions = %d\n', ...
    num_predictions);

fprintf('Number of GNN nodes       = %d\n', ...
    num_nodes);


%% ============================================================
% 6. BASIC GNN ARRAY CHECKS
% ============================================================

if size(G.v_pred, 1) ~= num_predictions || ...
   size(G.p_pred, 1) ~= num_predictions

    error( ...
        'u_pred, v_pred and p_pred have inconsistent numbers of samples.');

end

if size(G.v_pred, 2) ~= num_nodes || ...
   size(G.p_pred, 2) ~= num_nodes

    error( ...
        'u_pred, v_pred and p_pred have inconsistent numbers of nodes.');

end

dt_gnn = G.delta_t(:);

if length(dt_gnn) ~= num_predictions
    error( ...
        'Number of GNN delta_t values does not match predictions.');
end


%% ============================================================
% 7. CHECK COMSOL <-> GNN ALIGNMENT
% ============================================================

fprintf('\n========================================\n');
fprintf('CHECKING COMSOL <-> GNN ALIGNMENT\n');
fprintf('========================================\n');

% With skip_initial = 0:
%
% GNN prediction 1:
%       X_0 -> X_1
%
% GNN prediction 2:
%       X_1 -> X_2
%
% ...
%
% Therefore:
%
% number of predictions = number of COMSOL snapshots - 1

if num_predictions ~= num_transitions

    error( ...
        ['COMSOL/GNN transition mismatch.\n' ...
         'COMSOL transitions = %d\n' ...
         'GNN predictions    = %d'], ...
        num_transitions, ...
        num_predictions);

end


% Compare every delta_t
dt_difference = abs(dt_comsol - dt_gnn);

max_dt_error = max(dt_difference);

fprintf('Maximum |dt_COMSOL - dt_GNN| = %.15e s\n', ...
    max_dt_error);


% Numerical tolerance
dt_tolerance = ...
    100 * eps(max(abs(dt_comsol)));

if max_dt_error > dt_tolerance

    error( ...
        ['COMSOL and GNN delta_t arrays are not aligned.\n' ...
         'Maximum difference = %.15e s\n' ...
         'Tolerance          = %.15e s'], ...
        max_dt_error, ...
        dt_tolerance);

end


fprintf('\nCOMSOL and GNN are correctly aligned.\n');


%% ============================================================
% 8. SHOW FIRST TRANSITIONS
% ============================================================

fprintf('\n========================================\n');
fprintf('FIRST TRANSITIONS\n');
fprintf('========================================\n');

num_to_print = min(5, num_predictions);

for k = 1:num_to_print

    fprintf( ...
        ['k = %d | ' ...
         't_prev = %.8e | ' ...
         't_target = %.8e | ' ...
         'dt = %.8e\n'], ...
        k, ...
        t_comsol(k), ...
        t_comsol(k+1), ...
        dt_gnn(k));

end


fprintf('\n========================================\n');
fprintf('INITIAL PIPELINE READY\n');
fprintf('========================================\n');
%% ============================================================
% 9. FIRST STATIONARY BDF1 TEST
%
% Reproduce one transition:
%
%       X_k  ->  X_(k+1)
%
% using a Stationary Navier-Stokes problem with
%
%       F = rho * (u_k - u) / dt
%
% where u_k and v_k are read DIRECTLY from sol1.
%
% IMPORTANT:
%   GNN initial guess is NOT used yet.
% ============================================================

fprintf('\n========================================\n');
fprintf('FIRST STATIONARY BDF1 TEST\n');
fprintf('========================================\n');

% MATLAB / GNN transition index
k = 1000;

% Previous and target times
t_prev   = t_comsol(k);
t_target = t_comsol(k+1);

% Time-step size
dt = dt_comsol(k);

fprintf('Transition k = %d\n', k);
fprintf('t_prev       = %.15e s\n', t_prev);
fprintf('t_target     = %.15e s\n', t_target);
fprintf('dt           = %.15e s\n', dt);

%% ============================================================
% 10. SET dt PARAMETER
% ============================================================

dt_str = sprintf('%.17g[s]', dt);

model.param.set('dt_step', dt_str);

fprintf('\ndt_step set to: %s\n', dt_str);

%% ============================================================
% 11. GET LAMINAR FLOW AND VOLUME FORCE
% ============================================================

spf = model.component('comp1').physics('spf');
vf  = spf.feature('vf1');

%% ============================================================
% 12. DEFINE BDF1-EQUIVALENT VOLUME FORCE
% ============================================================

fprintf('\n========================================\n');
fprintf('SETTING BDF1 VOLUME FORCE\n');
fprintf('========================================\n');



% ------------------------------------------------------------
% Previous solution from sol1
%
% k identifies the stored COMSOL solution corresponding to
% the INPUT state of GNN prediction k:
%
%       X_k_previous  ->  X_k_target
%
% In MATLAB:
%
%       k = 1    -> first stored solution (t = t_comsol(1))
%       k = 2    -> second stored solution
%       ...
% ------------------------------------------------------------

u_prev_expr = sprintf( ...
    "withsol('sol1',u,setind(t,%d))", ...
    k);

v_prev_expr = sprintf( ...
    "withsol('sol1',v,setind(t,%d))", ...
    k);


% ------------------------------------------------------------
% BDF1-equivalent force
%
% Fx = rho*(u_prev - u)/dt
% Fy = rho*(v_prev - v)/dt
% ------------------------------------------------------------

Fx = sprintf( ...
    'spf.rho*(%s-u)/dt_step', ...
    u_prev_expr);

Fy = sprintf( ...
    'spf.rho*(%s-v)/dt_step', ...
    v_prev_expr);


% ------------------------------------------------------------
% Set Volume Force
% ------------------------------------------------------------

vf.set('F', {Fx; Fy; '0'});


fprintf('Fx = %s\n', Fx);
fprintf('Fy = %s\n', Fy);


%% ============================================================
% 13. CREATE STATIONARY SOLVER SEQUENCE
% ============================================================

fprintf('\n========================================\n');
fprintf('CREATING STATIONARY SOLVER SEQUENCE\n');
fprintf('========================================\n');

% Generate the solver sequence associated with Study 3
% without solving the stationary problem yet
model.study('std3').createAutoSequences('sol');

fprintf('Stationary solver sequence created.\n');

%% ============================================================
% 14. CONFIGURE BASELINE INITIAL GUESS
%
% Baseline:
%
%       previous state in F = X_k
%       Newton initial guess = X_k
%
% The stationary solver therefore starts from the previous
% time-dependent COMSOL solution.
% ============================================================

fprintf('\n========================================\n');
fprintf('CONFIGURING BASELINE INITIAL GUESS\n');
fprintf('========================================\n');

% Dependent Variables node of stationary solver sol3
v1 = model.sol('sol3').feature('v1');

% Use an existing COMSOL solution as initial guess
v1.set('initmethod', 'sol');

% Initial guess comes from the time-dependent solution
v1.set('initsol', 'sol1');

% Use exactly the previous state X_k
v1.set('solnum', num2str(k));

fprintf('Initial guess source = sol1\n');
fprintf('Solution number      = %d\n', k);
fprintf('Initial guess time   = %.15e s\n', t_prev);

%% ============================================================
% 15. RUN BASELINE
% ============================================================

fprintf('\n========================================\n');
fprintf('RUNNING BASELINE\n');
fprintf('========================================\n');

tic;

try

    model.sol('sol3').runAll();

    baseline_elapsed_time = toc;
    baseline_converged = true;

    fprintf('\n========================================\n');
    fprintf('BASELINE CONVERGED\n');
    fprintf('========================================\n');

    fprintf('Elapsed time = %.6f s\n', ...
        baseline_elapsed_time);

catch ME

    baseline_elapsed_time = toc;
    baseline_converged = false;

    fprintf('\n========================================\n');
    fprintf('BASELINE FAILED\n');
    fprintf('========================================\n');

    fprintf('Elapsed time = %.6f s\n', ...
        baseline_elapsed_time);

    fprintf('%s\n', ME.message);

    rethrow(ME);

end

%% ============================================================
% 16. STORE BASELINE SOLUTION
% ============================================================

P_eval = G.node_coordinates.';

u_baseline = mphinterp(model, 'u', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

v_baseline = mphinterp(model, 'v', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

p_baseline = mphinterp(model, 'p', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

u_baseline = u_baseline(:);
v_baseline = v_baseline(:);
p_baseline = p_baseline(:);

fprintf('Baseline solution stored.\n');

%% ============================================================
% 17. GET GNN PREDICTION
%
% For transition k:
%
%       X_k -> X_(k+1)
%
% G.u_pred(k,:), G.v_pred(k,:), G.p_pred(k,:)
% contain the GNN prediction of X_(k+1).
% ============================================================

fprintf('\n========================================\n');
fprintf('PREPARING GNN INITIAL GUESS\n');
fprintf('========================================\n');

% GNN node coordinates
x_gnn = G.node_coordinates(:,1);
y_gnn = G.node_coordinates(:,2);

% GNN prediction of the next state
u_gnn = G.u_pred(k,:).';
v_gnn = G.v_pred(k,:).';
p_gnn = G.p_pred(k,:).';

fprintf('Transition k = %d\n', k);
fprintf('Number of GNN nodes = %d\n', length(u_gnn));


% Files used by COMSOL interpolation functions
u_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\u_gnn.txt';

v_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\v_gnn.txt';

p_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\p_gnn.txt';

%% ============================================================
% 18. WRITE GNN PREDICTION TO COMSOL FILES
% ============================================================

writematrix( ...
    [x_gnn, y_gnn, u_gnn], ...
    u_gnn_file, ...
    'Delimiter', 'space');

writematrix( ...
    [x_gnn, y_gnn, v_gnn], ...
    v_gnn_file, ...
    'Delimiter', 'space');

writematrix( ...
    [x_gnn, y_gnn, p_gnn], ...
    p_gnn_file, ...
    'Delimiter', 'space');

fprintf('GNN prediction written to interpolation files.\n');
%% ============================================================
% 19. REFRESH GNN INTERPOLATION FUNCTIONS
% ============================================================

model.func('int4').refresh();
model.func('int5').refresh();
model.func('int6').refresh();

fprintf('GNN interpolation functions refreshed.\n');

%% ============================================================
% 20. CHECK PHYSICS INITIAL VALUES
% ============================================================

fprintf('\n========================================\n');
fprintf('CHECKING GNN INITIAL VALUES\n');
fprintf('========================================\n');

init1 = model.component('comp1') ...
    .physics('spf') ...
    .feature('init1');

Pinit = mphgetproperties(init1);

fprintf('Velocity initial values = %s\n', Pinit.u_init);
fprintf('Pressure initial value  = %s\n', Pinit.p_init);

%% ============================================================
% 21. CONFIGURE GNN INITIAL GUESS
%
% IMPORTANT:
%   The stationary equations are NOT changed.
%
%   Baseline:
%       initial guess = X_k from sol1
%
%   GNN:
%       initial guess = X_hat_(k+1) from physics Initial Values
% ============================================================

fprintf('\n========================================\n');
fprintf('CONFIGURING GNN INITIAL GUESS\n');
fprintf('========================================\n');

v1 = model.sol('sol3').feature('v1');

% Use the Initial Values defined in Laminar Flow:
%
%   u = uGNN(x,y)
%   v = vGNN(x,y)
%   p = pGNN(x,y)
%
v1.set('initmethod', 'init');

fprintf('Initial guess source = physics Initial Values\n');
fprintf('u0 = uGNN(x,y)\n');
fprintf('v0 = vGNN(x,y)\n');
fprintf('p0 = pGNN(x,y)\n');

%% ============================================================
% 22. RUN GNN-INITIALIZED SOLVER
% ============================================================

fprintf('\n========================================\n');
fprintf('RUNNING GNN INITIAL GUESS\n');
fprintf('========================================\n');

tic;

try

    model.sol('sol3').runAll();

    gnn_elapsed_time_solver = toc;
    gnn_converged = true;

    fprintf('\n========================================\n');
    fprintf('GNN-INITIALIZED SOLVER CONVERGED\n');
    fprintf('========================================\n');

    fprintf('Elapsed time = %.6f s\n', ...
        gnn_elapsed_time_solver);

catch ME

    gnn_elapsed_time_solver = toc;
    gnn_converged = false;

    fprintf('\n========================================\n');
    fprintf('GNN-INITIALIZED SOLVER FAILED\n');
    fprintf('========================================\n');

    fprintf('Elapsed time = %.6f s\n', ...
        gnn_elapsed_time_solver);

    fprintf('%s\n', ME.message);

    rethrow(ME);

end

%% ============================================================
% 23. STORE GNN-INITIALIZED SOLUTION
% ============================================================

fprintf('\n========================================\n');
fprintf('STORING GNN-INITIALIZED SOLUTION\n');
fprintf('========================================\n');

u_gnn_solution = mphinterp(model, 'u', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

v_gnn_solution = mphinterp(model, 'v', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

p_gnn_solution = mphinterp(model, 'p', ...
    'coord', P_eval, ...
    'dataset', 'dset3');

u_gnn_solution = u_gnn_solution(:);
v_gnn_solution = v_gnn_solution(:);
p_gnn_solution = p_gnn_solution(:);

%% ============================================================
% 24. COMPARE BASELINE AND GNN FINAL SOLUTIONS
% ============================================================

fprintf('\n========================================\n');
fprintf('BASELINE vs GNN FINAL SOLUTION\n');
fprintf('========================================\n');

du = u_gnn_solution - u_baseline;
dv = v_gnn_solution - v_baseline;
dp = p_gnn_solution - p_baseline;

rmse_u = sqrt(mean(du.^2));
rmse_v = sqrt(mean(dv.^2));
rmse_p = sqrt(mean(dp.^2));

max_u = max(abs(du));
max_v = max(abs(dv));
max_p = max(abs(dp));

fprintf('RMSE u = %.15e\n', rmse_u);
fprintf('RMSE v = %.15e\n', rmse_v);
fprintf('RMSE p = %.15e\n', rmse_p);

fprintf('\n');

fprintf('MAX |du| = %.15e\n', max_u);
fprintf('MAX |dv| = %.15e\n', max_v);
fprintf('MAX |dp| = %.15e\n', max_p);

%% ============================================================
% 25. TIMING SUMMARY
% ============================================================

fprintf('\n========================================\n');
fprintf('TIMING SUMMARY\n');
fprintf('========================================\n');

fprintf('Baseline = %.6f s\n', baseline_elapsed_time);
fprintf('GNN      = %.6f s\n', gnn_elapsed_time_solver);

speedup = baseline_elapsed_time / gnn_elapsed_time_solver;

fprintf('Speedup  = %.6fx\n', speedup);