function cfg = gnn_comsol_config()

% ============================================================
% GNN <-> COMSOL PIPELINE CONFIGURATION
%
% Single source of truth for every file path used by the
% GNN-COMSOL MATLAB scripts (prepare_gnn_comsol_pipeline,
% complete_pipeline_single_step, complete_pipeline_all_timesteps).
%
% Update the paths here when the COMSOL model, the GNN virtual
% environment, or the trained run directory change - every
% script picks up the change automatically.
% ============================================================

% COMSOL model.
% Study 1 / sol1 must already have been computed and saved
% by first_database.m.
cfg.model_file = ...
    '\\nl-filer1\users$\giovanni\Desktop\Comsol simulations\channel2d_gnn_initial_guess_test.mph';

% Dataset generated by first_database.m
cfg.dataset_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\channel2d_physics_variables_gnn_dataset.mat';

% Python executable inside the GNN virtual environment
cfg.python_exe = ...
    'C:\Users\giovanni\gnn\.venv\Scripts\python.exe';

% Python inference script
cfg.python_script = ...
    'C:\Users\giovanni\gnn\scripts\evaluate_test.py';

% Trained GNN run
cfg.run_dir = ...
    'C:\Users\giovanni\gnn\outputs\bsms_powerful_all_geometries_20260904_162806';

% File produced by evaluate_test.py
cfg.gnn_predictions_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\gnn_predictions.mat';

% Files used by the COMSOL GNN interpolation functions
% (int4 = u, int5 = v, int6 = p)
cfg.u_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\u_gnn.txt';

cfg.v_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\v_gnn.txt';

cfg.p_gnn_file = ...
    'C:\Users\giovanni\.comsol\v64\llmatlab\p_gnn.txt';

end
